### ISSUE TITLE
Dossier module vide

### ISSUE THREAD

**Issue by XavierBeheydt** [sorayaeldjama/csv_parser#1]
Hello, je remarque que dans ton commit je vois pas de fichier dans le dossier module `csv_parser`? Est-ce normal ?

**Comment by sorayaeldjama** [comment]
Hello Il dans les fichier la ou y a les fichier python

Le sam. 27 mars 2021 à 15:31, Didier Bröska ***@***.***> a
écrit :

**Comment by XavierBeheydt** [comment]
oui car il y a rien dans ton dossier j'ai l'impression

**Comment by sorayaeldjama** [comment]
oui justement c est bizarre
sur mon repertoire local y en a

**Comment by XavierBeheydt** [comment]
Bon à priori c'est bon maintenant celà ?
