### ISSUE TITLE
Package or module -> `__init__.py`

### ISSUE THREAD

**Issue by XavierBeheydt** [sorayaeldjama/csv_parser#6]
Alors je vois du code dupliqué dans ton fichier [`__init__.py`](https://github.com/sorayaeldjama/csv_parser/blob/1f0c32095d710ebeb6e9c6e58ec3c3e12edc9859/csv_parser/__init__.py). Le fichier `__init__.py` permet de faire un package ou un module (*oui selon l'emplacement`). Et le code que l'ont place dedans est en générale des constantes globales ou du code ultra générique (*comme des fonction alias par exemple*).

Sinon, nous écrivons rien dedans presque.

**Comment by sorayaeldjama** [comment]
ah oui juste j ai fait un essaye de code j ai pas vollu essayer sur l original de coup j ai oublier de le supprimer dsl

**Comment by XavierBeheydt** [comment]
Alors tu as tout retiré dedans mais tu peux laisser une docstring. Car celle-ci permet de faire une doc explicative du package.

D'ailleurs je vais ouvrir une autre issue à propre des constantes que tu as mis dans `cli.py`.
