### ISSUE TITLE
Commiting

### ISSUE THREAD

**Issue by XavierBeheydt** [sorayaeldjama/csv_parser#8]
Hello, bon je vois tes commit -> commit 1, commit 2. LE fait de mettre des message de commit dte permet de savoir ce qu'il a été fait dans le "dit" commit. Mais avec ce genre de message *commit 1*, bah on ne sait pas ce qui a été fait au premier coup d'oeil.

**Comment by sorayaeldjama** [comment]
d'accord donc je dois ecrire ce que j ai fait

**Comment by XavierBeheydt** [comment]
Bah le mieux c'est de mettre une petite description de ce que tu as commit

**Comment by sorayaeldjama** [comment]
d'accords
